### ISSUE TITLE
Peer code review - Justin Laabs

### ISSUE THREAD

**Issue by laabsky** [malikra/TTS-RM#1]
# Design/Code Review 1

### Reviewer: Justin Laabs

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| o Well explained, easy to understand <br> o check grammar and sentence structure <br> o How far out can the tool be used? |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | o Simple and User-friendly <br> o include nav bar? <br> o  Add task details? |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| o Good ERD use <br> o No database design yet|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | o Well structured <br> o tests/code for one-many hibernate functionality <br> o Add Lombok to reduce code volume? |

**Comment by malikra** [comment]
Done!
