### ISSUE TITLE
Peer Code review

### ISSUE THREAD

**Issue by EliseJava** [malikra/TTS-RM#2]
# Design/Code Review 1

### Reviewer: Elise Strauss

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose <br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| The problem/solution is well defined and written.  It is a tool that I will find helpful to use. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |Provided excellent details on Application flow and screen design. Database design is in progress |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|1-to-many relationship is implemented and database is well underway. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.  |Have followed all the technology standards in the subject matter that we have covered.|

**Comment by pawaitemadisoncollege** [comment]
@EliseJava Any areas for improvement here?

**Comment by malikra** [comment]
Done !
